#!/usr/bin/env python3
"""
Integration Tests für opena15 - HTML Creator Agent
Port: 12360
Kürzel: htmlp

Tests:
1. Health Check
2. Root Endpoint
3. List Templates
4. Generate HTML (default template)
5. Generate HTML (with CSS framework)
6. Validate HTML (valid)
7. Validate HTML (invalid)
8. Preview HTML
9. Export HTML (file)
10. Export HTML (base64)
11. Command Endpoint (generate_html)
12. Strict JSON validation
"""

import sys
import json
import time
import base64
import requests
from pathlib import Path

# Config
BASE_URL = "http://127.0.0.1:12360"
BEARER_TOKEN = "c899b90d-faf8-485b-afa4-078357cf5313"
HEADERS = {
    "Authorization": f"Bearer {BEARER_TOKEN}",
    "Content-Type": "application/json"
}

# Test-Statistiken
total_tests = 12
passed_tests = 0
failed_tests = 0

def log_test(test_num: int, test_name: str, passed: bool, details: str = ""):
    """Test-Ergebnis loggen"""
    global passed_tests, failed_tests
    
    status = "✓" if passed else "✗"
    color = "\033[0;32m" if passed else "\033[0;31m"
    reset = "\033[0m"
    
    if passed:
        passed_tests += 1
    else:
        failed_tests += 1
    
    print(f"{color}[{status}] Test {test_num} ({test_name}): {'PASS' if passed else 'FAIL'}{reset}{f' - {details}' if details else ''}")

def test_1_health():
    """Test 1: Health Check"""
    try:
        resp = requests.get(f"{BASE_URL}/health", timeout=5)
        
        if resp.status_code != 200:
            log_test(1, "Health", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        # Check response structure
        required_keys = ["status", "service", "kuerzel", "port", "uptime_seconds", "templates_available", "jinja2_support"]
        missing = [k for k in required_keys if k not in data]
        
        if missing:
            log_test(1, "Health", False, f"Missing keys: {missing}")
            return
        
        # Validate values
        if data["status"] != "ok":
            log_test(1, "Health", False, f"Status not ok: {data['status']}")
            return
        
        if data["kuerzel"] != "htmlp":
            log_test(1, "Health", False, f"Wrong kürzel: {data['kuerzel']}")
            return
        
        if data["port"] != 12360:
            log_test(1, "Health", False, f"Wrong port: {data['port']}")
            return
        
        uptime = data["uptime_seconds"]
        templates = data["templates_available"]
        
        log_test(1, "Health", True, f"Uptime: {uptime:.2f}s, Templates: {templates}, Jinja2: {data['jinja2_support']}")
    
    except Exception as e:
        log_test(1, "Health", False, str(e))

def test_2_root():
    """Test 2: Root Endpoint"""
    try:
        resp = requests.get(f"{BASE_URL}/", timeout=5)
        
        if resp.status_code != 200:
            log_test(2, "Root", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        if "service" not in data or "kuerzel" not in data:
            log_test(2, "Root", False, "Missing service/kuerzel")
            return
        
        log_test(2, "Root", True)
    
    except Exception as e:
        log_test(2, "Root", False, str(e))

def test_3_list_templates():
    """Test 3: List Templates"""
    try:
        resp = requests.get(f"{BASE_URL}/templates/list", headers=HEADERS, timeout=5)
        
        if resp.status_code != 200:
            log_test(3, "List Templates", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        if "templates" not in data or "total" not in data:
            log_test(3, "List Templates", False, "Missing templates/total")
            return
        
        templates = data["templates"]
        total = data["total"]
        
        # Should have at least default template
        if total == 0:
            log_test(3, "List Templates", False, "No templates found")
            return
        
        log_test(3, "List Templates", True, f"Total: {total}, Templates: {templates}")
    
    except Exception as e:
        log_test(3, "List Templates", False, str(e))

def test_4_generate_default():
    """Test 4: Generate HTML (default template)"""
    try:
        payload = {
            "template_name": "default.html",
            "variables": {
                "title": "Test Page",
                "heading": "Integration Test",
                "content": "This is a test page generated by opena15."
            },
            "css_framework": "none",
            "title": "Test Page",
            "description": "Test description",
            "keywords": ["test", "html", "opena15"]
        }
        
        resp = requests.post(f"{BASE_URL}/generate", headers=HEADERS, json=payload, timeout=10)
        
        if resp.status_code != 200:
            log_test(4, "Generate Default", False, f"Status {resp.status_code}: {resp.text}")
            return
        
        data = resp.json()
        
        if not data.get("success"):
            log_test(4, "Generate Default", False, f"Generation failed: {data.get('message')}")
            return
        
        # Check HTML content
        html = data.get("html", "")
        if "Integration Test" not in html:
            log_test(4, "Generate Default", False, "HTML missing expected content")
            return
        
        # Check file path
        file_path = data.get("file_path")
        if not file_path:
            log_test(4, "Generate Default", False, "Missing file_path")
            return
        
        # Verify file exists
        if not Path(file_path).exists():
            log_test(4, "Generate Default", False, f"File not found: {file_path}")
            return
        
        file_size = data.get("file_size", 0)
        
        log_test(4, "Generate Default", True, f"File: {Path(file_path).name}, Size: {file_size} bytes")
    
    except Exception as e:
        log_test(4, "Generate Default", False, str(e))

def test_5_generate_with_css():
    """Test 5: Generate HTML (with CSS framework)"""
    try:
        payload = {
            "template_name": "default.html",
            "variables": {
                "heading": "Bootstrap Test",
                "content": "Testing CSS framework injection."
            },
            "css_framework": "bootstrap",
            "title": "Bootstrap Test Page"
        }
        
        resp = requests.post(f"{BASE_URL}/generate", headers=HEADERS, json=payload, timeout=10)
        
        if resp.status_code != 200:
            log_test(5, "Generate with CSS", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        if not data.get("success"):
            log_test(5, "Generate with CSS", False, f"Generation failed: {data.get('message')}")
            return
        
        html = data.get("html", "")
        
        # Check for Bootstrap CDN link
        if "bootstrap" not in html.lower():
            log_test(5, "Generate with CSS", False, "Bootstrap CSS not injected")
            return
        
        log_test(5, "Generate with CSS", True, "Bootstrap CSS injected")
    
    except Exception as e:
        log_test(5, "Generate with CSS", False, str(e))

def test_6_validate_valid():
    """Test 6: Validate HTML (valid)"""
    try:
        valid_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Valid HTML</title>
</head>
<body>
    <h1>Test</h1>
</body>
</html>"""
        
        payload = {
            "html": valid_html,
            "validation_level": "standard"
        }
        
        resp = requests.post(f"{BASE_URL}/validate", headers=HEADERS, json=payload, timeout=5)
        
        if resp.status_code != 200:
            log_test(6, "Validate Valid", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        if not data.get("valid"):
            errors = data.get("errors", [])
            log_test(6, "Validate Valid", False, f"Validation failed: {errors}")
            return
        
        warnings = data.get("warnings", [])
        info = data.get("info", {})
        
        log_test(6, "Validate Valid", True, f"Warnings: {len(warnings)}, Tags: {info.get('tag_count', 0)}")
    
    except Exception as e:
        log_test(6, "Validate Valid", False, str(e))

def test_7_validate_invalid():
    """Test 7: Validate HTML (invalid)"""
    try:
        invalid_html = """<div>
    <p>No html, head, or body tags
</div>"""
        
        payload = {
            "html": invalid_html,
            "validation_level": "standard"
        }
        
        resp = requests.post(f"{BASE_URL}/validate", headers=HEADERS, json=payload, timeout=5)
        
        if resp.status_code != 200:
            log_test(7, "Validate Invalid", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        # Should be invalid
        if data.get("valid"):
            log_test(7, "Validate Invalid", False, "Invalid HTML marked as valid")
            return
        
        errors = data.get("errors", [])
        
        # Should have errors
        if len(errors) == 0:
            log_test(7, "Validate Invalid", False, "No errors reported")
            return
        
        log_test(7, "Validate Invalid", True, f"Errors detected: {len(errors)}")
    
    except Exception as e:
        log_test(7, "Validate Invalid", False, str(e))

def test_8_preview():
    """Test 8: Preview HTML"""
    try:
        html = """<!DOCTYPE html>
<html>
<head><title>Preview Test</title></head>
<body><h1>Preview Content</h1></body>
</html>"""
        
        payload = {
            "html": html,
            "width": 1920,
            "height": 1080
        }
        
        resp = requests.post(f"{BASE_URL}/preview", headers=HEADERS, json=payload, timeout=5)
        
        if resp.status_code != 200:
            log_test(8, "Preview", False, f"Status {resp.status_code}")
            return
        
        # Preview returns HTML content
        preview_html = resp.text
        
        if "Preview Content" not in preview_html:
            log_test(8, "Preview", False, "Preview missing content")
            return
        
        # Check viewport meta was injected
        if "viewport" not in preview_html.lower():
            log_test(8, "Preview", False, "Viewport meta not injected")
            return
        
        log_test(8, "Preview", True, f"Preview rendered ({len(preview_html)} chars)")
    
    except Exception as e:
        log_test(8, "Preview", False, str(e))

def test_9_export_file():
    """Test 9: Export HTML (file)"""
    try:
        html = """<!DOCTYPE html>
<html><head><title>Export Test</title></head><body><p>Test</p></body></html>"""
        
        payload = {
            "html": html,
            "filename": "test_export.html",
            "format": "html"
        }
        
        resp = requests.post(f"{BASE_URL}/export", headers=HEADERS, json=payload, timeout=5)
        
        if resp.status_code != 200:
            log_test(9, "Export File", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        if not data.get("success"):
            log_test(9, "Export File", False, f"Export failed: {data.get('message')}")
            return
        
        file_path = data.get("file_path")
        if not file_path:
            log_test(9, "Export File", False, "Missing file_path")
            return
        
        # Verify file exists
        if not Path(file_path).exists():
            log_test(9, "Export File", False, f"File not found: {file_path}")
            return
        
        log_test(9, "Export File", True, f"File: {Path(file_path).name}")
    
    except Exception as e:
        log_test(9, "Export File", False, str(e))

def test_10_export_base64():
    """Test 10: Export HTML (base64)"""
    try:
        html = "<html><body>Base64 Test</body></html>"
        
        payload = {
            "html": html,
            "filename": "test_base64.html",
            "format": "base64"
        }
        
        resp = requests.post(f"{BASE_URL}/export", headers=HEADERS, json=payload, timeout=5)
        
        if resp.status_code != 200:
            log_test(10, "Export Base64", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        if not data.get("success"):
            log_test(10, "Export Base64", False, f"Export failed: {data.get('message')}")
            return
        
        b64_data = data.get("base64_data")
        if not b64_data:
            log_test(10, "Export Base64", False, "Missing base64_data")
            return
        
        # Verify can decode
        try:
            decoded = base64.b64decode(b64_data).decode("utf-8")
            if "Base64 Test" not in decoded:
                log_test(10, "Export Base64", False, "Decoded content mismatch")
                return
        except Exception as e:
            log_test(10, "Export Base64", False, f"Decode error: {e}")
            return
        
        log_test(10, "Export Base64", True, f"Base64 length: {len(b64_data)} chars")
    
    except Exception as e:
        log_test(10, "Export Base64", False, str(e))

def test_11_command_endpoint():
    """Test 11: Command Endpoint (generate_html)"""
    try:
        payload = {
            "action": "generate_html",
            "params": {
                "template_name": "default.html",
                "variables": {
                    "heading": "Command Test",
                    "content": "Testing Option-2-Flow compatibility."
                },
                "css_framework": "none",
                "title": "Command Test"
            }
        }
        
        resp = requests.post(f"{BASE_URL}/command", headers=HEADERS, json=payload, timeout=10)
        
        if resp.status_code != 200:
            log_test(11, "Command Endpoint", False, f"Status {resp.status_code}")
            return
        
        data = resp.json()
        
        if data.get("action") != "generate_html":
            log_test(11, "Command Endpoint", False, f"Wrong action: {data.get('action')}")
            return
        
        if not data.get("success"):
            log_test(11, "Command Endpoint", False, f"Command failed: {data.get('result', {}).get('message')}")
            return
        
        result = data.get("result", {})
        html = result.get("html", "")
        
        if "Command Test" not in html:
            log_test(11, "Command Endpoint", False, "HTML missing expected content")
            return
        
        log_test(11, "Command Endpoint", True, f"Action: {data['action']}, HTML generated")
    
    except Exception as e:
        log_test(11, "Command Endpoint", False, str(e))

def test_12_strict_json():
    """Test 12: Strict JSON validation"""
    try:
        # Send request with unknown field
        payload = {
            "html": "<html><body>Test</body></html>",
            "validation_level": "standard",
            "unknown_field": "should_be_rejected"
        }
        
        resp = requests.post(f"{BASE_URL}/validate", headers=HEADERS, json=payload, timeout=5)
        
        # Should return 422 (Validation Error)
        if resp.status_code == 422:
            log_test(12, "Strict JSON", True, "Unknown fields rejected (422)")
            return
        
        # If 200, check if field was silently ignored (bad)
        if resp.status_code == 200:
            log_test(12, "Strict JSON", False, "Unknown field accepted (should reject)")
            return
        
        log_test(12, "Strict JSON", False, f"Unexpected status: {resp.status_code}")
    
    except Exception as e:
        log_test(12, "Strict JSON", False, str(e))

# =============================================================================
# MAIN TEST RUNNER
# =============================================================================

def main():
    print("=" * 70)
    print("  opena15 - HTML Creator Agent Integration Tests")
    print("  Port: 12360")
    print("=" * 70)
    print("")
    
    # Wait for service to be ready
    print("Warte auf Service-Initialisierung...")
    time.sleep(2)
    
    # Run all tests
    test_1_health()
    test_2_root()
    test_3_list_templates()
    test_4_generate_default()
    test_5_generate_with_css()
    test_6_validate_valid()
    test_7_validate_invalid()
    test_8_preview()
    test_9_export_file()
    test_10_export_base64()
    test_11_command_endpoint()
    test_12_strict_json()
    
    # Summary
    print("")
    print("=" * 70)
    print(f"Total: {total_tests}, Passed: {passed_tests}, Failed: {failed_tests}, Rate: {(passed_tests/total_tests*100):.1f}%")
    
    if failed_tests == 0:
        print("\033[0;32m✅ ALL TESTS PASSED\033[0m")
        sys.exit(0)
    else:
        print(f"\033[0;31m❌ {failed_tests} TEST(S) FAILED\033[0m")
        sys.exit(1)

if __name__ == "__main__":
    main()
